In [3]:
import pandas as pd #data processing
import numpy as np #linear algebra

# ON BINARY DATA

In [30]:
df = pd.read_csv("../dataset/heart.csv")

In [31]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
#train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size = 0.2, random_state = 2)

In [7]:

from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 

In [8]:
# Create objects
mdl1= LogisticRegression()
mdl2 = DecisionTreeClassifier()

In [9]:
#fit into training data 
mdl1.fit(X_train, y_train)
mdl2.fit(X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [10]:
#prediction
y_pred1= mdl1.predict(X_test)
y_pred2 = mdl2.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score

In [12]:
#accuracy
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9016393442622951
Accuracy of Decision Trees 0.819672131147541


In [13]:
confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]], dtype=int64)

In [14]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))


Logistic Regression Confusion Matrix



0   1
0  26   6
1   0  29

In [15]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  24   8
1   3  26

In [16]:
data = {'Actual Label' : y_test, 'LR_Prediction' : y_pred1, "DT_Prediciton" : y_pred2}
result = pd.DataFrame(data)

In [17]:
result.sample(10)

Actual Label  LR_Prediction  DT_Prediciton
296             0              1              0
65              1              1              1
184             0              0              0
140             1              1              1
240             0              0              0
178             0              0              0
157             1              1              1
182             0              1              1
276             0              0              0
209             0              0              0

In [18]:
#for logistic regression
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625


In [19]:
#for decision tree 
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

Precision -  0.7647058823529411
Recall -  0.896551724137931
F1 score -  0.8253968253968255


In [20]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [21]:
recall_score(y_test,y_pred2,average=None)

array([0.75      , 0.89655172])

# ON MULTICLASSIFICATION

In [65]:
df = pd.read_csv("../dataset/MNIST DigitalRecognizer/train.csv")

In [27]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size = 0.2, random_state = 2)

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

cl1= LogisticRegression()
cl2 = DecisionTreeClassifier()

In [58]:
cl1.fit(X_train, y_train)
cl2.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [59]:
y_pred1 = cl1.predict(X_test)
y_pred2 = cl2.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.03278688524590164
Accuracy of Decision Trees 0.04918032786885246


In [49]:
print("Logistic Regression Confusion Matrix\n")
res = pd.DataFrame(confusion_matrix(y_test,y_pred1))
res.iloc[:10,:10]

Logistic Regression Confusion Matrix



0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0  1  0  0
2  0  0  0  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0  1  0  0
4  1  0  0  0  0  0  0  2  0  0
5  0  0  0  0  0  0  0  1  0  0
6  0  0  0  0  0  0  0  0  0  0
7  0  0  0  0  0  0  0  1  0  0
8  0  0  0  0  0  0  0  1  0  0
9  0  0  0  0  0  0  0  1  0  0